### ISSUE TITLE
Fetch beatmap descriptions for !addset command

### ISSUE THREAD

**Issue by Lekuruu** [osuTitanic/banchobot#202]

**Comment by kanaarima** [comment]
doesnt !beatmap_info do this?

**Comment by kanaarima** [comment]
unless you meant something else

**Comment by Lekuruu** [comment]
Notice how the new beatmapsets all have „None“ in their description. That is the thing i want to fetch.

**Comment by kanaarima** [comment]
I see, may look into this sometime

**Comment by Lekuruu** [comment]
Finally resolved in: https://github.com/osuTitanic/banchobot/commit/8545d45e37bd2e58c1de9d6f954e7d820e81b79c
